### ISSUE TITLE
improve the way of neovim downloading on remote machine

### ISSUE THREAD

**Issue by littenglt** [amitds1997/remote-nvim.nvim#80]
## Describe the bug

Sometimes, remote machines can't connect github.com 100% successfully. 
so I encountered issue as below: 
![image](https://github.com/amitds1997/remote-nvim.nvim/assets/146831861/5f6ab0eb-19aa-4946-b344-a8ca07e1060e)

if possible, can we change the way of downloading neovim from:
http://ppa.launchpad.net/neovim-ppa/stable/ubuntu/

that's would be helpful

**Comment by amitds1997** [comment]
Hey, thanks for bringing this up. I get your frustration, however, I would prefer to keep the dependency on the official releases so that I can reliably track any upstream issues.

Depending upon the PPA release creates a few problems:
1. It will only solve the issue for Ubuntu.
2. I will have to track issues that happen in Ubuntu releases instead of only tracking Neovim installation.
3. It would interfere with the system environment (I assume) since we would install it through `apt-get`(??).
4. `ppa.launchpad.net` can also face the same issue (maybe?).

Due to these reasons, and to solve your issue as well, here's what I propose:
1. We cache the Neovim version locally on your system when it once downloads. During successive runs, we just copy the binary over (we would keep per-OS version copy to avoid wrong binary getting copied).
2. If cache is not found, we fetch from `github.com`.

This would not completely solve the problem but would remove the dependency on GitHub once the cache is downloaded. How does that sound?

**Comment by amitds1997** [comment]
I would have to put more thoughts into this to flesh it out completely before implementing it. But what you can do right now is override the install script.

The current installation script is at [scripts/install.sh](https://github.com/amitds1997/remote-nvim.nvim/blob/main/scripts/neovim_install.sh). You can provide your own installation script instead and pass it's path to `neovim_install_script_path` so that that would be copied to remote and executed to install Neovim. For more information, see the advanced configuration section in [Installation](https://github.com/amitds1997/remote-nvim.nvim#-installation).

We pass an input path of the type `<script> -v <neovim-version> -d <home-directory>/.remote-nvim` and the end result should be a neovim binary at `<home-directory>/.remote-nvim/neovim-downloads/<neovim-version>/bin/nvim`. As long as this happens, you can choose any method to install Neovim.

This might sound like a lot (and it is), but that is how you can alleviate this right now.

**Comment by littenglt** [comment]
Sorry, turned it off by mistake.

**Comment by littenglt** [comment]
You are right. It is not good to only depend on the PPA due to some users may use it on other OS
The easiest thing  I can think of is add new choice:  copy the executeable binary directly from the local machine to the remote machine
This is helpful if some of those machine can't connect the release website successfully.
if the neovim can't run on the remote machine, that is problem the owner should deal with.

**Comment by amitds1997** [comment]
> The easiest thing I can think of is add new choice: copy the executable binary directly from the local machine to the remote machine 

This completely makes sense and is something I planned to do it in the future as part of ["completely offline" feature](https://github.com/amitds1997/remote-nvim.nvim/blob/v0.1.3/README.md#-features). 

Would downloading on your local and then transferring that on to the remote machine work for your use case? I would update the documentation with the path where all the releases need to be dumped. So, if you have a manual way to do it once, you can do it manually and the plugin would not try to connect to GitHub at all.

**Comment by littenglt** [comment]
> This completely makes sense and is something I planned to do it in the future as part of ["completely offline" feature](https://github.com/amitds1997/remote-nvim.nvim/blob/v0.1.3/README.md#-features).
> 
That's great!
> So, would downloading on your local and then transferring that on to the remote machine work for your use case? I would update the documentation with the path where all the releases need to be dumped. So, if you have a manual way to do it once, you can do it manually and the plugin would not try to connect to GitHub at all.
> 
Sure, I  can give it a try if your documentation describle the step in details. 
> Why I cannot simply copy over just the binary is that Neovim ships with some other files along with the release which are I think it might need to run. I will experiment if that is possible at all, though.
Yes, it would be simple and reliable if everything related on the current machine was copied to the remote machine

**Comment by amitds1997** [comment]
I integrated this in #81. Try out the [Offline mode](https://github.com/amitds1997/remote-nvim.nvim?tab=readme-ov-file#-offline-mode) and let me know how how you feel about it and if you face any issues or have suggestions to improve it.
